language: ruby
bundler_args: --without development --path vendor/bundle
rvm:
  - 1.9.3
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

