language: ruby
bundler_args: --without development --path vendor/bundle
rvm:
  - 2.0.0
gemfile:
  - Gemfile
env:
  - RAILS_ENV=test
branches:
  only:
    - master
env:
  - DB=sqlite
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
after_failure:
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
