language: ruby
bundler_args: --without development --path vendor/bundle
rvm:
  - 1.9.3
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - DB=sqlite
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake spec
